[fuzz]
runs = 1000

[profile.default]
contracts = 'src/contracts'
gas_reports = ["*"]
libs = ['lib']
optimizer = true              # Enable or disable the solc optimizer
optimizer_runs = 200          # The number of optimizer runs
out = 'out'
src = 'src'
verbosity = 3                 # The verbosity of tests
